# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]

jobs:
  install:
    name: Deactivate
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pkill -f uvicorn

  deploy:
    name: 🚀 CI-CD
    runs-on: [self-hosted]
    needs: install
    env:
      WORK_DIR: /root/actions-runner/_work/image-scrap-product-remommend/image-scrap-product-remommend
      DEPLOY_PATH: /var/www/app
    steps:
      - name: Move directory to live
        run: |
          cp -rf $WORK_DIR/. /var/www/app

      - name: 🚀 Deploy
        run: |
          cd /var/www/app
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run
        run: |
          cd /var/www/app
          source .venv/bin/activate
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 & disown
