# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]

jobs:
  install:
    name: deactivate
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pkill -f gunicorn

  # deploy:
  #   name: 🚀 CD
  #   runs-on: [self-hosted]
  #   needs: install
  #   env:
  #       WORK_DIR: /actions-runner/_work/image-scrap-product-remommend/image-scrap-product-remommend
  #       DEPLOY_PATH: /var/www/
  #   steps:
  #       - name: Move directory to live
  #         run: |
  #             cp -rf $WORK_DIR/. /var/www/app

  #       - name: 🚀 Deploy
  #         run: |
  #           pkill -f gunicorn
